export const START_TIME = "START_TIME";

//Operatore action types
export const GET_OPERATORE = "GET_OPERATORE";
export const SELECT_OPERATORE = "SELECT_OPERATORE";

//Barcode action types
export const SELECT_BARCODE = "SELECT_BARCODE";
export const BARCODE_CHECK = "BARCODE_CHECK";
export const GET_CLIENTE = "GET_CLIENTE";
export const GET_ARTICOLO = "GET_ARTICOLO";
export const GET_NOTE = "GET_NOTE";
export const GET_QUANTITA = "GET_QUANTITA";
export const GET_RICETTA_ANCORANTE = "GET_RICETTA_ANCORANTE";
export const GET_RICETTA_RIPORTO = "GET_RICETTA_RIPORTO";
export const GET_NUM_PEZZI = "GET_NUM_PEZZI";
export const GET_DATA_ORA = "GET_DATA_ORA";
export const GET_QUANTITA_ANCORANTE_UTILIZ = "GET_QUANTITA_ANCORANTE_UTILIZ";
export const GET_QUANTITA_RIPORTO_UTILZ = "GET_QUANTITA_RIPORTO_UTILZ";
export const GET_DURATA_LAVORAZIONE = "GET_DURATA_LAVORAZIONE";

//TimeStamp action types
export const SET_START_ATTREZZAGGIO = "SET_START_ATTREZZAGGIO";
export const ADD_SOSPENDI_DATE = "ADD_SOSPENDI_DATE";
export const ADD_RIPRENDI_DATE = "ADD_RIPRENDI_DATE";
export const SET_COMPLETATO_ATTREZZAGGIO = "SET_COMPLETATO_ATTREZZAGGIO";

//Attrezzaggio status action types
export const ATTREZZAGGIO_START_STATUS = "ATTREZZAGGIO_START_STATUS";
export const ATTREZZAGGIO_SOSPESO_STATUS = "ATTREZZAGGIO_SOSPESO_STATUS";
export const ATTREZZAGGIO_RIPRESO_STATUS = "ATTREZZAGGIO_RIPRESO_STATUS";
export const ATTREZZAGGIO_COMPLETATO_STATUS = "ATTREZZAGGIO_COMPLETATO_STATUS";
export const CHIUSURA_ODP = "CHIUSURA_ODP";

//Riporto status action types
export const RIPORTO_COMPLETATO_STATUS = "RIPORTO_COMPLETATO_STATUS";
